#!/bin/bash
git submodule update --init --recursive
(mkdir ardtool; cd ardtool; wget https://bitbucket.org/multidest/ardronetools/downloads/ardrone-toolchain.tar.xz; tar xf ardrone-toolchain.tar.xz)
(chmod u+w -R ardtool; rm -f ardtool/ardrone-toolchain.tar.xz)
(mkdir -p config/softsim/build; cd config/softsim/build; cmake ..)
(mkdir -p config/ardrone/build; cd config/ardrone/build; cmake ..)
