/*==============================================================================
** File Name: to_iloads.c
**
** Title:     TO iloads table definition
**
** $Author: $
** $Revision: $
** $Date:  $
**
** Purpose:   To provide the TO iloads table for default data config.
**
** Functions Contained:
**    None
**
**
** Limitations, Assumptions, External Events, and Notes:
**  1.   None
**
** Modification History:
**   MM/DD/YY  SCR/SDR     Author          DESCRIPTION
**   --------  ----------  -------------   -----------------------------
**   mm/dd/yy  $$$SCRxxxx  C. Writer       Build #: Code Started
**
**
**==============================================================================
*/

#ifndef _TO_CONFIG_
#define _TO_CONFIG_

#ifdef	__cplusplus
extern "C" {
#endif


/*
** Pragmas
*/

/*
** Include Files
*/
#include "app.h"
#include "tbl.h"
#include "cfe_tbl_filedef.h"
#include "to_platform_cfg.h"
#include "to_mission_cfg.h"
#include "msg_ids.h"

/*
** Local Defines
*/


/*
** Local Structure Declarations
*/

CFE_TBL_FileDef_t CFE_TBL_FileDef =
{
    "to_ConfigTable", "TO.to_config", "TO config table",
    "to_config.tbl", sizeof(TO_Table_t)
};

/*
** Default TO iLoad table data
*/

#define TO_QUEUE_PILOT			0
#define TO_QUEUE_HIGH			1
#define TO_QUEUE_MEDIUM			2
#define TO_QUEUE_LOW			3
#define TO_QUEUE_EVENTS			4
#define TO_QUEUE_FWD_VIDEO		5
#define TO_QUEUE_CFDP			6

#define TO_CHANNEL_PILOT		0
#define TO_CHANNEL_TLM			1
#define TO_CHANNEL_CFDP			2
#define TO_CHANNEL_FWD_VIDEO	3

TO_Table_t to_ConfigTable =
{
	TO_MAX_TLM_SUBSCRIPTIONS,
	0x1ffd,
	1000,
    {
    	/* 0 - 9 */
    	{CF_CONFIG_TLM_MID, 									1, TO_QUEUE_HIGH},
		{CF_HK_TLM_MID, 										1, TO_QUEUE_HIGH},
		{CF_SPACE_TO_GND_PDU_MID, 								32, TO_QUEUE_CFDP},
		{CF_TRANS_TLM_MID, 										1, TO_QUEUE_HIGH},
    	{CFE_ES_APP_TLM_MID,    								1, TO_QUEUE_HIGH},
    	{CFE_ES_HK_TLM_MID,										1, TO_QUEUE_HIGH},
    	{CFE_ES_MEMSTATS_TLM_MID,								1, TO_QUEUE_HIGH},
    	{CFE_ES_SHELL_TLM_MID,  								32,	TO_QUEUE_MEDIUM},
    	{CFE_EVS_EVENT_MSG_MID, 								32, TO_QUEUE_EVENTS},
    	{CFE_EVS_HK_TLM_MID,    								1, TO_QUEUE_HIGH},

    	/* 10 - 19 */
    	{CFE_SB_ALLSUBS_TLM_MID,								32, TO_QUEUE_MEDIUM},
    	{CFE_SB_HK_TLM_MID,     								1, TO_QUEUE_HIGH},
    	{CFE_SB_ONESUB_TLM_MID, 								32, TO_QUEUE_MEDIUM},
    	{CFE_SB_STATS_TLM_MID,  								1, TO_QUEUE_HIGH},
    	{CFE_TBL_HK_TLM_MID,    								1, TO_QUEUE_HIGH},
    	{CFE_TBL_REG_TLM_MID,   								1, TO_QUEUE_HIGH},
    	{CFE_TIME_DIAG_TLM_MID, 								1, TO_QUEUE_HIGH},
    	{CFE_TIME_HK_TLM_MID,   								1, TO_QUEUE_HIGH},
        {TO_HK_TLM_MID,     									1, TO_QUEUE_HIGH},
    	{HS_HK_TLM_MID, 										1, TO_QUEUE_HIGH},

    	/* 20 - 29 */
    	{SCH_DIAG_TLM_MID, 										1, TO_QUEUE_HIGH},
    	{SCH_HK_TLM_MID,         								1, TO_QUEUE_HIGH},
    	{EIM_HK_TLM_MID, 										1, TO_QUEUE_HIGH},
    	{FM_HK_TLM_MID,  										1, TO_QUEUE_HIGH},
    	{FM_OPEN_FILES_TLM_MID, 								1, TO_QUEUE_HIGH},
    	{FM_FREE_SPACE_TLM_MID, 								1, TO_QUEUE_HIGH},
    	{FM_FILE_INFO_TLM_MID, 									1, TO_QUEUE_HIGH},
    	{FM_DIR_LIST_TLM_MID, 									1, TO_QUEUE_HIGH},
    	{CS_HK_TLM_MID, 										1, TO_QUEUE_HIGH},
    	{DS_HK_TLM_MID, 										1, TO_QUEUE_HIGH},

    	/* 60 - 69 */
    	{DS_DIAG_TLM_MID, 										1, TO_QUEUE_HIGH},
    	{HK_HK_TLM_MID, 										1, TO_QUEUE_HIGH},
    	{HK_COMBINED_PKT1_MID, 									1, TO_QUEUE_HIGH},
    	{HK_COMBINED_PKT2_MID, 									1, TO_QUEUE_HIGH},
    	{HK_COMBINED_PKT3_MID, 									1, TO_QUEUE_HIGH},
    	{HK_COMBINED_PKT4_MID, 									1, TO_QUEUE_HIGH},
    	{HK_COMBINED_PKT5_MID, 									1, TO_QUEUE_HIGH},
    	{HK_COMBINED_PKT6_MID, 									1, TO_QUEUE_HIGH},
    	{HK_COMBINED_PKT7_MID, 									1, TO_QUEUE_HIGH},
    	{HK_COMBINED_PKT8_MID, 									1, TO_QUEUE_HIGH},

    	/* 70 - 79 */
    	{HK_COMBINED_PKT9_MID, 									1, TO_QUEUE_HIGH},
    	{HK_COMBINED_PKT10_MID,									1, TO_QUEUE_HIGH},
    	{LC_HK_TLM_MID,											1, TO_QUEUE_HIGH},
    	{LC_SAMPLE_AP_MID,										1, TO_QUEUE_HIGH},
    	{MD_HK_TLM_MID,											1, TO_QUEUE_HIGH},
    	{MD_DWELL_PKT_MID_BASE,									1, TO_QUEUE_HIGH},
    	{SCH_DIAG_TLM_MID,										1, TO_QUEUE_HIGH},
    	{SCH_HK_TLM_MID,										1, TO_QUEUE_HIGH},
    	{DS_HK_TLM_MID, 										1, TO_QUEUE_HIGH},
    	{DS_DIAG_TLM_MID,										1, TO_QUEUE_HIGH},

    	/* 80 - 89 */
    	{MM_HK_TLM_MID, 										1, TO_QUEUE_HIGH},
    	{SC_HK_TLM_MID, 										1, TO_QUEUE_HIGH},
    	{NAV_HK_TLM_MID,										1, TO_QUEUE_HIGH},
    	{FIXHAWK_HK_TLM_MID,									1, TO_QUEUE_HIGH},
    	{FIXHAWK_MAVLINK_OUT_MSG_MID,							50, TO_QUEUE_PILOT},
    	{MAVLINK_CFS_MSG_ID_ATTITUDE_QUATERNION_COV,			1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_ATTITUDE_QUATERNION,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_ATTITUDE_TARGET,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_ATTITUDE,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_AUTH_KEY,							1, TO_QUEUE_HIGH},

    	/* 90 - 99 */
    	{MAVLINK_CFS_MSG_ID_AUTOPILOT_VERSION,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_BATTERY_STATUS,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_CHANGE_OPERATOR_CONTROL_ACK,		1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_CHANGE_OPERATOR_CONTROL,			1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_COMMAND_ACK,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_COMMAND_INT,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_COMMAND_LONG,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_DATA_STREAM,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_DATA_TRANSMISSION_HANDSHAKE,		1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_DEBUG_VECT,							1, TO_QUEUE_HIGH},

    	/* 100 - 109 */
    	{MAVLINK_CFS_MSG_ID_DEBUG,								1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_DISTANCE_SENSOR,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_ENCAPSULATED_DATA,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_FILE_TRANSFER_PROTOCOL,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_GLOBAL_POSITION_INT_COV,			1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_GLOBAL_POSITION_INT,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_GLOBAL_VISION_POSITION_ESTIMATE,	1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_GPS_GLOBAL_ORIGIN,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_GPS_INJECT_DATA,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_GPS_RAW_INT,						1, TO_QUEUE_HIGH},

    	/* 110 - 119 */
    	{MAVLINK_CFS_MSG_ID_GPS_RTK,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_GPS_STATUS,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_GPS2_RAW,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_HIGHRES_IMU,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_HIL_CONTROLS,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_HIL_GPS,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_HIL_OPTICAL_FLOW,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_HIL_RC_INPUTS_RAW,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_HIL_SENSOR,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_HIL_STATE_QUATERNION,				1, TO_QUEUE_HIGH},

    	/* 120 - 129 */
    	{MAVLINK_CFS_MSG_ID_HIL_STATE,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_LOCAL_POSITION_NED_COV,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET,	1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_LOCAL_POSITION_NED,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_LOG_DATA,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_LOG_ENTRY,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_LOG_ERASE,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_LOG_REQUEST_DATA,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_LOG_REQUEST_END,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_LOG_REQUEST_LIST,					1, TO_QUEUE_HIGH},

    	/* 130 - 139 */
    	{MAVLINK_CFS_MSG_ID_MANUAL_CONTROL,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MANUAL_SETPOINT,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MEMORY_VECT,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_ACK,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_CLEAR_ALL,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_COUNT,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_CURRENT,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_ITEM_INT,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_ITEM_REACHED,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_ITEM,						1, TO_QUEUE_HIGH},

    	/* 140 - 149 */
    	{MAVLINK_CFS_MSG_ID_MISSION_REQUEST_LIST,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_REQUEST_PARTIAL_LIST,		1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_REQUEST,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_SET_CURRENT,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_WRITE_PARTIAL_LIST,			1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MISSION_VALUE_FLOAT,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_NAMED_VALUE_FLOAT,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_NAMED_VALUE_INT,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_NAV_CONTROLLER_OUTPUT,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_OMNIDIRECTIONAL_FLOW,				1, TO_QUEUE_HIGH},

    	/* 150 - 159 */
    	{MAVLINK_CFS_MSG_ID_OPTICAL_FLOW,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_PARAM_REQUEST_LIST,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_PARAM_REQUEST_READ,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_PARAM_SET,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_PARAM_VALUE,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_PING,								1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_POSITION_TARGET_GLOBAL_INT,			1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_POSITION_TARGET_LOCAL_NED,			1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_POWER_STATUS,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_RADIO_STATUS,						1, TO_QUEUE_HIGH},

    	/* 160 - 169 */
    	{MAVLINK_CFS_MSG_ID_RAW_IMU,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_RAW_PRESSURE,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_RC_CHANNELS_OVERRIDE,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_RC_CHANNELS_RAW,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_RC_CHANNELS_SCALED,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_RC_CHANNELS,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_REQUEST_DATA_STREAM,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SAFETY_ALLOWED_AREA,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SAFETY_SET_ALLOWED_AREA,			1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SCALED_IMU,							1, TO_QUEUE_HIGH},

    	/* 170 - 179 */
    	{MAVLINK_CFS_MSG_ID_SCALED_IMU2,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SCALED_PRESSURE,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SERIAL_CONTROL,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SERVO_OUTPUT_RAW,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SET_ATTITUDE_TARGET,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SET_GPS_GLOBAL_ORIGIN,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SET_MODE,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SET_POSITION_TARGET_GLOBAL_INT,		1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SET_POSITION_TARGET_LOCAL_NED,		1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SIM_STATE,							1, TO_QUEUE_HIGH},

    	/* 180 - 189 */
    	{MAVLINK_CFS_MSG_ID_STATUSTEXT,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SYS_STATUS,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SYSTEM_TIME,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_TERRAIN_CHECK,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_TERRAIN_DATA,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_TERRAIN_REPORT,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_TERRAIN_REQUEST,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_V2_EXTENSION,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_VFR_HUD,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_VICON_POSITION_ESTIMATE,			1, TO_QUEUE_HIGH},

    	/* 190 - 199 */
    	{MAVLINK_CFS_MSG_ID_VISION_POSITION_ESTIMATE,			1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_VISION_SPEED_ESTIMATE,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_ATTITUDE_CONTROL,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_BRIEF_FEATURE,						1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_DETECTION_STATS,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_IMAGE_AVAILABLE,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_IMAGE_TRIGGER_CONTROL,				1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_IMAGE_TRIGGERED,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_MARKER,								1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_ONBOARD_HEALTH,						1, TO_QUEUE_HIGH},

    	/* 200 - 209 */
    	{MAVLINK_CFS_MSG_ID_PATTERN_DETECTED,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_POINT_OF_INTEREST_CONNECTION,		1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_POINT_OF_INTEREST,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_POSITION_CONTROL_SETPOINT,			1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_RAW_AUX,							1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SET_CAM_SHUTTER,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_SET_POSITION_CONTROL_OFFSET,		1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_WATCHDOG_COMMAND,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_WATCHDOG_HEARTBEAT,					1, TO_QUEUE_HIGH},
    	{MAVLINK_CFS_MSG_ID_WATCHDOG_PROCESS_INFO,				1, TO_QUEUE_HIGH},

    	/* 210 - 219 */
    	{MAVLINK_CFS_MSG_ID_WATCHDOG_PROCESS_STATUS,			1, TO_QUEUE_HIGH},
    	{VID_FWD_CAM_FRAME_MID, 								1, 	TO_QUEUE_FWD_VIDEO},
    	{EIM_NAVDATA_TIME_MID, 									1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_RAW_MEASURES_MID,							1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_PRESSURE_RAW_MID,							1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_MAGNETO_MID,								1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_WIND_SPEED_MID, 							1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_KALMAN_PRESSURE_MID,						1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_ZIMMU_3000_MID, 							1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_PHYS_MEASURES_MID,							1,  TO_QUEUE_MEDIUM},

    	/* 220 - 229 */
    	{EIM_NAVDATA_GYRO_OFFSETS_MID, 							1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_EULER_ANGLES_MID, 							1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_REFERENCES_MID, 							1,  TO_QUEUE_MEDIUM},
        {EIM_NAVDATA_TRIMS_MID, 								1,  TO_QUEUE_MEDIUM},
        {EIM_NAVDATA_RC_REFERENCES_MID, 						1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_PWM_MID, 									1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_ALTITUDE_MID, 								1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_VISION_RAW_MID, 							1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_VISION_MID, 								1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_VISION_PERF_MID, 							1,  TO_QUEUE_MEDIUM},

    	/* 230 - 239 */
    	{EIM_NAVDATA_TRACKERS_SEND_MID, 						1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_DETECT_MID, 								1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_VISION_OF_MID, 							1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_WATCHDOG_MID, 								1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_ADC_DATA_FRAME_MID, 						1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_VIDEO_STREAM_MID, 							1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_HDVIDEO_MID, 								1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_GAMES_MID, 								1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_WIFI_MID, 									1,  TO_QUEUE_MEDIUM},
    	{EIM_NAVDATA_DEMO_MID,  								1,  TO_QUEUE_MEDIUM},

    	/* 240 - 249 */
    	{NAVSPARK_NACK_TLM_MID, 								1, TO_QUEUE_HIGH},
    	{NAVSPARK_SOFTWARE_VERSION_TLM_MID, 					1, TO_QUEUE_HIGH},
    	{NAVSPARK_ACK_TLM_MID, 									1, TO_QUEUE_HIGH},
    	{NAVSPARK_SBAS_STATUS_TLM_MID, 							1, TO_QUEUE_HIGH},
    	{NAVSPARK_POS_UPDATE_RATE_TLM_MID, 						1, TO_QUEUE_HIGH},
    	{NAVSPARK_GLONASS_EPHEM_TLM_MID, 						1, TO_QUEUE_HIGH},
    	{NAVSPARK_GPS_EPHEM_TLM_MID, 							1, TO_QUEUE_HIGH},
    	{NAVSPARK_MEAS_EPOCH_TLM_MID, 							1, TO_QUEUE_HIGH},
    	{NAVSPARK_SV_AND_CHANNEL_STATUS_TLM_MID, 				1, TO_QUEUE_HIGH},
    	{NAVSPARK_RCV_NAV_STATUS_TLM_MID, 						1, TO_QUEUE_HIGH},

    	/* 250 - 259 */
    	{NAVSPARK_GPS_SUBFRM_DATA_TLM_MID, 						1, TO_QUEUE_HIGH},
    	{NAVSPARK_SOFTWARE_CRC_TLM_MID, 						1, TO_QUEUE_HIGH},
    	{NAVSPARK_RAW_MEAS_TLM_MID, 							1, TO_QUEUE_HIGH},
    	{NAVSPARK_BIN_MEAS_DATA_OUT_STATUS_TLM_MID, 			1, TO_QUEUE_HIGH},
    	{NAVSPARK_GNSS_DATUM_TLM_MID, 							1, TO_QUEUE_HIGH},
    	{NAVSPARK_GNSS_DOPMASK_TLM_MID, 						1, TO_QUEUE_HIGH},
    	{NAVSPARK_ELEV_AND_CNR_MASK_TLM_MID, 					1, TO_QUEUE_HIGH},
    	{NAVSPARK_QZSS_STATUS_TLM_MID, 							1, TO_QUEUE_HIGH},
    	{NAVSPARK_SAEE_STATUS_TLM_MID, 							1, TO_QUEUE_HIGH},
    	{NAVSPARK_HK_TLM_MID, 									1, TO_QUEUE_HIGH},

		/* 260 - 269 */
		{NAVSPARK_BOOT_STATUS_TLM_MID, 							1, TO_QUEUE_HIGH},
    	{NAVSPARK_EXT_NMEA_MSG_INT_TLM_MID, 					1, TO_QUEUE_HIGH},
    	{NAVSPARK_INT_DET_STATUS_TLM_MID, 						1, TO_QUEUE_HIGH},
    	{NAVSPARK_GPS_PARAM_SRCH_ENG_NUM_TLM_MID, 				1, TO_QUEUE_HIGH},
    	{NAVSPARK_GNSS_NAV_MODE_TLM_MID, 						1, TO_QUEUE_HIGH},
    	{NAVSPARK_1PPS_PULSE_WIDTH_TLM_MID, 					1, TO_QUEUE_HIGH},
    	{NAVSPARK_1PPS_FREQ_OUT_TLM_MID, 						1, TO_QUEUE_HIGH},
    	{NAVSPARK_POWER_MODE_TLM_MID,							1, TO_QUEUE_HIGH},
    	{NAVSPARK_NAV_DATA_TLM_MID,								1, TO_QUEUE_HIGH},
    	{HS_CUSTOM_HK_TLM_MID,									1, TO_QUEUE_HIGH},

		/* 270 - 279 */
    	{TO_UNUSED, 											1, TO_QUEUE_HIGH},
    	{TO_UNUSED, 											1, TO_QUEUE_HIGH},
    	{TO_UNUSED, 											1, TO_QUEUE_HIGH},
    	{TO_UNUSED, 											1, TO_QUEUE_HIGH},
    	{TO_UNUSED, 											1, TO_QUEUE_HIGH},
    	{TO_UNUSED, 											1, TO_QUEUE_HIGH},
    	{TO_UNUSED, 											1, TO_QUEUE_HIGH},
    	{TO_UNUSED, 											1, TO_QUEUE_HIGH},
    	{TO_UNUSED, 											1, TO_QUEUE_HIGH},
    	{TO_UNUSED, 											1, TO_QUEUE_HIGH}
    },
	{
		{ TO_QUEUE_ENABLED,  50,  10000,     TO_CHANNEL_PILOT, 	0, 0, 0, 0},
		{ TO_QUEUE_ENABLED,  10,    500,       TO_CHANNEL_TLM, 	0, 0, 0, 0},
		{ TO_QUEUE_ENABLED,  30,    250,       TO_CHANNEL_TLM, 	0, 0, 0, 0},
		{ TO_QUEUE_ENABLED, 100,     20,       TO_CHANNEL_TLM, 	0, 0, 0, 0},
		{ TO_QUEUE_ENABLED, 100,     20,       TO_CHANNEL_TLM, 	0, 0, 0, 0},
		{ TO_QUEUE_ENABLED,   1, 100000, TO_CHANNEL_FWD_VIDEO,	0, 0, 0, 0},
		{ TO_QUEUE_ENABLED, 100,     20,       TO_CHANNEL_CFDP, 	0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,      0, 0, 0, 0, 0, 0},

		{ TO_QUEUE_UNUSED,    0,      0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,      0, 0, 0, 0, 0, 0},

		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},

		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},

		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0},
		{ TO_QUEUE_UNUSED,    0,    0, 0, 0, 0, 0, 0}
	},
	{
		{TO_CHANNEL_ENABLED, "127.0.0.1", 14550, 0 },
		{TO_CHANNEL_ENABLED, "127.0.0.1",  5011, 0 },
		{TO_CHANNEL_ENABLED, "127.0.0.1",  5012, 0 },
		{TO_CHANNEL_ENABLED, "127.0.0.1",  1234, 0 }
	}
};



/*
** External Global Variables
*/

/*
** Global Variables
*/

/*
** Local Variables
*/

/*
** Local Function Prototypes
*/

#ifdef	__cplusplus
}
#endif

#endif /* _TO_CONFIG_ */
